# Run unit tests on GitHub actions manually, and for each pull request
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch: null

jobs:
  test:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
            type: windows
          - runs-on: macos-15-intel
            arch: osx-x64
            type: posix
          - runs-on: ubuntu-latest
            arch: linux-x64
            type: posix
          - runs-on: windows-11-arm
            arch: win-arm64
            type: windows
          - runs-on: macos-15
            arch: osx-arm64
            type: posix
          - runs-on: ubuntu-24.04-arm
            arch: linux-arm64
            type: posix

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Run tests
      run: dotnet test
